const dataHero = {
  "cloud1":{
   "Aamon":{
    info:["Assassin","2021"],
    skin:["Starlight","Soul Vessel"]},
   "Akai":{
    info:["Tank","2016"],
    skin:["Halloween","Anniversary","Kungfu panda"]},
   "Aldous":{
    info:["Fighter","2018"],
    skin:["Transformers","Blazing","Mistbender","M1","Collector"]},
   "Alice":{
    info:["Mage/Tank","2016"],
    skin:["Luckybox"]},
   "Alpha":{
    info:["Fighter","2017"],
    skin:["Luckybox","Collector","Legend"]},
   "Alucard":{
    info:["Fighter/Assassin","2016"],
    skin:["Luckybox","Lightborn","Star wars","Legend"]},
   "Angela":{
    info:["Support","2018"],
    skin:["Starlight Gold","Sanrio","Kishin","Aspirant","Collector"]},
   "Argus":{
    info:["Fighter","2017"],
    skin:["Starlight","Star wars","Custom Epic"]},
   "Arlott":{
    info:["Fighter/Assassin","2023"],
    skin:["Starlight","Collector"]},
   "Atlas":{
    info:["Tank","2020"],
    skin:["Msc","Starlight","Collector"]},
   "Aulus":{
    info:["Fighter","2021"],
    skin:["Special"]},
   "Aurora":{
    info:["Mage","2017"],
    skin:["Kof","Zodiac","Collector"]},
   "Badang":{
    info:["Fighter","2019"],
    skin:["Zodiac","Collector","Saint seiya Gold"]},
   "Balmond":{
    info:["Fighter","2016"],
    skin:["Special","Epic","Collector"]},
   "Bane":{
    info:["Fighter/Mage","2016"],
    skin:["Epic"]},
   "Barats":{
    info:["Tank/Fighter","2020"],
    skin:["Epic"]},
   "Baxia":{
    info:["Tank","2019"],
    skin:["NoFile"]},
   "Beatrix":{
    info:["Marksman","2021"],
    skin:["Starlight","Mseries"]},
   "Belerick":{
    info:["Tank","2018"],
    skin:["Epic"]},
   "Benedetta":{
    info:["Assassin/Fighter","2020"],
    skin:["Special","Starlight","Mpl","Ducati","Covenant","Collector"]},
   "Brody":{
    info:["Marksman","2020"],
    skin:["Stun","Neobeast","Champion","Collector"]},
   "Bruno":{
    info:["Marksman","2016"],
    skin:["Starlight","Neymar","Dawning"]},
   "Carmilla":{
    info:["Support/Tank","2020"],
    skin:["Epic"]},
   "Cecilion":{
    info:["Mage","2020"],
    skin:["Starlight","Hunter x hunter","Collector"]},
   "Change":{
    info:["Mage","2018"],
    skin:["Luckybox","Lunar fest","Aspirant","Sanrio"]},
   "Chip":{
    info:["Support/Tank","2024"],
    skin:["Elite"]},
   "Chou":{
    info:["Fighter","2016"],
    skin:["Luckybox","Champion","Dawning","Saint seiya Gold","Kof","Stun"]},
   "Cici":{
    info:["Fighter","2023"],
    skin:["Starlight"]},
   "Claude":{
    info:["Marksman","2018"],
    skin:["Luckybox","Blazing","M6","Prime","Sanrio","Valentine"]},
   "Clint":{
    info:["Marksman","2016"],
    skin:["Epic","M2","Mythic","Collector"]},
   "Cyclops":{
    info:["Mage","2017"],
    skin:["Star wars","Collector"]},
   "Diggie":{
    info:["Support","2017"],
    skin:["Epic"]},
   "Dyrroth":{
    info:["Fighter","2019"],
    skin:["Venom","Kof","Hunter x hunter","Collector"]},
   "Edith":{
    info:["Tank/Marksman","2021"],
    skin:["Mpl","Clouds","Collector"]},
   "Esmeralda":{
    info:["Tank/Mage","2019"],
    skin:["Blazing","Dawning","Collector"]},
   "Estes":{
    info:["Support","2017"],
    skin:["Sparkle","Champion"]},
   "Eudora":{
    info:["Mage","2016"],
    skin:["Starlight","Luckybox","Atomic"]}
},"cloud2":{
   "Fanny":{
    info:["Assassin","2016"],
    skin:["Luckybox","Christmas","Lightborn","Summer","Valentine","Aot","Aspirants"]},
   "Faramis":{
    info:["Support/Mage","2019"],
    skin:["Summer","Mythic"]},
   "Floryn":{
    info:["Support","2021"],
    skin:["Sanrio","Collector"]},
   "Franco":{
    info:["Tank","2016"],
    skin:["Epic","Luckybox","Mpl","Blazing"]},
   "Fredrinn":{
    info:["Fighter/Tank","2022"],
    skin:["Neobeast","Sparkle"]},
   "Freya":{
    info:["Fighter","2016"],
    skin:["Epic"]},
   "Gatotkaca":{
    info:["Tank/Fighter","2017"],
    skin:["Epic","Luckybox"]},
   "Gloo":{
    info:["Tank","2021"],
    skin:["Special"]},
   "Gord":{
    info:["Mage","2016"],
    skin:["Epic","Starlight","Starlight Gold","Legend"]},
   "Granger":{
    info:["Marksman","2019"],
    skin:["Create","Transformers","Valentine","Lightborn","Exorcist","Collector","Legend"]},
   "Grock":{
    info:["Tank/Fighter","2017"],
    skin:["Epic","Venom"]},
   "Guinevere":{
    info:["Fighter","2019"],
    skin:["Epic","Summer","Kof","Legend"]},
   "Gusion":{
    info:["Assassin","2018"],
    skin:["Epic","Kof","11.11","Collector","Legend"]},
   "Hanabi":{
    info:["Marksman","2018"],
    skin:["Soul vessel","Allstar","Collector"]},
   "Hanzo":{
    info:["Assassin","2018"],
    skin:["Collector"]},
   "Harith":{
    info:["Mage","2018"],
    skin:["Lightborn","Champion","Collector","Hunter x hunter"]},
   "Harley":{
    info:["Assassin/Mage","2017"],
    skin:["Epic","Collector"]},
   "Hayabusa":{
    info:["Assassin","2016"],
    skin:["Epic","Starlight Gold","11.11","Exorcist","Kakashi"]},
   "Helcurt":{
    info:["Assassin","2017"],
    skin:["Zodiac","Starlight"]},
   "Hilda":{
    info:["Fighter/Tank","2017"],
    skin:["Zodiac"]},
   "Hylos":{
    info:["Tank","2017"],
    skin:["Epic"]},
   "Irithel":{
    info:["Marksman","2017"],
    skin:["Luckybox","Zodiac","Ducati"]},
   "Ixia":{
    info:["Marksman","2023"],
    skin:["Starlight"]},
   "Jawhead":{
    info:["Fighter","2018"],
    skin:["Mpl","Allstar","Collector"]},
   "Johnson":{
    info:["Tank/Support","2017"],
    skin:["Luckybox","Saber","Legend"]},
   "Joy":{
    info:["Assassin","2022"],
    skin:["Starlight"]},
   "Julian":{
    info:["Assassin/Fighter","2022"],
    skin:["Jujutsu kaisen","Hunter x hunter","Fatcat"]},
},"cloud3":{
   "Kadita":{
    info:["Mage/Assassin","2018"],
    skin:["Starlight","Create","Mpl"]},
   "Kagura":{
    info:["Mage","2016"],
    skin:["Epic","Luckybox","Starlight","Starlight Gold","Exorcist","Clouds"]},
   "Kaja":{
    info:["Support/Fighter","2018"],
    skin:["Epic","Luckybox"]},
   "Kalea":{
    info:["Support/Fighter","2025"],
    skin:["Sakura"]},
   "Karina":{
    info:["Assassin","2016"],
    skin:["Epic","Luckybox","Kof","Zodiac"]},
   "Karrie":{
    info:["Marksman","2017"],
    skin:["Luckybox","Starlight Gold","Kishin"]},
   "Khaleed":{
    info:["Fighter","2020"],
    skin:["Epic"]},
   "Khufra":{
    info:["Tank","2019"],
    skin:["Starlight","Collector","Custom Epic"]},
   "Kimmy":{
    info:["Marksman/Mage","2018"],
    skin:["Starlight","Luckybox","Star wars","Dragon tamer"]},
   "Lancelot":{
    info:["Assassin","2017"],
    skin:["Luckybox","Christmas","Dawning","Zodiac","Kishin","Champion"]},
   "Lapu lapu":{
    info:["Fighter","2017"],
    skin:["Special","Starlight","Collector"]},
   "Layla":{
    info:["Marksman","2016"],
    skin:["Starlight","Aspirant","Collector"]},
   "Leomord":{
    info:["Fighter","2018"],
    skin:["Luckybox","Abyss","Ducati"]},
   "Lesley":{
    info:["Marksman/Assassin","2018"],
    skin:["Luckybox","Starlight","Starlight Gold","Aspirants","Collector","Fatcat","Covenant","Legend"]},
   "Ling":{
    info:["Assassin","2019"],
    skin:["Starlight","Kungfu panda","Dragon tamer","Mworld","Neobeast","Collector"]},
   "Lolita":{
    info:["Support/Tank","2016"],
    skin:["NoFile"]},
   "Luo yi":{
    info:["Mage","2020"],
    skin:["Epic","Starlight","Collector"]},
   "Lukas":{
    info:["Fighter","2024"],
    skin:["NoFile"]},
   "Lunox":{
    info:["Mage","2018"],
    skin:["Luckybox","Zodiac","Legend"]},
   "Lylia":{
    info:["Mage","2019"],
    skin:["Starlight","Neobeast"]},
   "Martis":{
    info:["Fighter","2018"],
    skin:["Luckybox","Starlight","Aot","Zodiac"]},
   "Masha":{
    info:["Fighter/Tank","2019"],
    skin:["Kof"]},
   "Mathilda":{
    info:["Support/Assassin","2020"],
    skin:["Epic","Mpl"]},
   "Melissa":{
    info:["Marksman","2022"],
    skin:["Starlight","Jujutsu kaisen","Sparkle","Collector"]},
   "Minotaur":{
    info:["Tank/Support","2016"],
    skin:["Zodiac"]},
   "Minsitthar":{
    info:["Fighter","2018"],
    skin:["Starlight","Collector"]},
   "Miya":{
    info:["Marksman","2016"],
    skin:["Starlight","Christmas","Atomic","Collector","Legend"]},
   "Moskov":{
    info:["Marksman","2017"],
    skin:["Luckybox","Abyss","Allstar"]},
},"cloud4":{
   "Nana":{
    info:["Mage","2016"],
    skin:["Mistbender","Collector"]},
   "Natalia":{
    info:["Assassin","2016"],
    skin:["Collector"]},
   "Natan":{
    info:["Marksman","2021"],
    skin:["Collector"]},
   "Nolan":{
    info:["Assassin","2023"],
    skin:["11.11"]},
   "Novaria":{
    info:["Mage","2023"],
    skin:["Starlight","Collector"]},
   "Odette":{
    info:["Mage","2017"],
    skin:["Starlight","Create","Lunar fest","Zodiac"]},
   "Paquito":{
    info:["Fighter/Assassin","2021"],
    skin:["Starlight","Kof","Fmvp","Pacquiao","Collector"]},
   "Pharsa":{
    info:["Mage","2017"],
    skin:["Epic","Starlight","Msc","Collector","Neobeast"]},
   "Phoveus":{
    info:["Fighter","2021"],
    skin:["Starlight"]},
   "Popol and kupa":{
    info:["Marksman","2020"],
    skin:["Transformers","Collector","Allstar"]},
   "Rafaela":{
    info:["Support","2016"],
    skin:["Mpl","Lunar fest"]},
   "Roger":{
    info:["Fighter/Marksman","2017"],
    skin:["Epic","M3","Prime"]},
   "Ruby":{
    info:["Fighter","2017"],
    skin:["Epic","Aspirants","Collector"]},
   "Saber":{
    info:["Assassin","2016"],
    skin:["Luckybox","Legend"]},
   "Selena":{
    info:["Assassin/Mage","2018"],
    skin:["Epic","Abyss","Stun","Zodiac"]},
   "Silvanna":{
    info:["Fighter","2019"],
    skin:["Collector","Valentine","Fatcat"]},
   "Sun":{
    info:["Fighter","2016"],
    skin:["Starlight","Collector"]},
   "Suyou":{
    info:["Assassin/Fighter","2024"],
    skin:["Sasuke"]},
   "Terizla":{
    info:["Fighter/Tank","2019"],
    skin:["Epic","Collector"]},
   "Thamuz":{
    info:["Fighter","2018"],
    skin:["Starlight","Kungfu panda"]},
   "Tigreal":{
    info:["Tank","2016"],
    skin:["Lightborn","Starlight"]},
   "Uranus":{
    info:["Tank","2018"],
    skin:["Epic"]},
},"cloud5":{
   "Vale":{
    info:["Mage","2019"],
    skin:["Starlight Gold","Dawning","Gaara","Collector"]},
   "Valentina":{
    info:["Mage","2021"],
    skin:["Starlight","Msc","Collector"]},
   "Valir":{
    info:["Mage","2018"],
    skin:["Kof","Saint seiya Gold","Collector","Legend"]},
   "Vexana":{
    info:["Mage","2017"],
    skin:["Zenith","Collector"]},
   "Wanwan":{
    info:["Marksman","2019"],
    skin:["11.11","Mworld","Collector"]},
   "X borg":{
    info:["Fighter","2019"],
    skin:["Transformers","11.11"]},
   "Xavier":{
    info:["Mage","2022"],
    skin:["Clouds","Jujutsu kaisen"]},
   "Yi sun shin":{
    info:["Assassin/Marksman","2017"],
    skin:["Starlight","Collector"]},
   "Yin":{
    info:["Fighter/Assassin","2022"],
    skin:["Aot","Jujutsu kaisen","Mworld"]},
   "Yu zhong":{
    info:["Fighter","2020"],
    skin:["Starlight","Collector","M5","Prime"]},
   "Yve":{
    info:["Mage","2021"],
    skin:["Elite"]},
   "Zetian":{
     info:["Mage","2025"],
     skin:["NoFile"]},
   "Zhask":{
    info:["Mage","2017"],
    skin:["Luckybox","Starlight","Zodiac"]},
   "Zhuxin":{
    info:["Mage","2024"],
    skin:["Starlight"]},
   "Zilong":{
    info:["Fighter/Assassin","2016"],
    skin:["Epic","Lunar fest"]},
 }
};
