const dataHero = [{
 hero:"Miya",
 name:"Moonlight Archer",
 role:"Marksman",
 release:2016,
 Specialty:"Finisher/Damage",
 lane:"Gold Lane",
 region:"Azrya Woodlands",
 id:1},{
 hero:"Balmond",
 name:"Bloody Beast",
 role:"Fighter",
 release:2016,
 Specialty:"Damage/Regen",
 lane:"EXP Lane",
 region:"The Barren Lands",
 id:2},{
 hero:"Saber",
 name:"Wandering Sword",
 role:"Assassin",
 release:2016,
 Specialty:"Charge/Finisher",
 lane:"Jungle/Roaming",
 region:"Laboratory 1718",
 id:3},{
 hero:"Alice",
 name:"Queen of Blood",
 role:"Mage/Tank",
 release:2016,
 Specialty:"Charge/Regen",
 lane:"EXP Lane/Jungle",
 region:"The Barren Lands",
 id:4},{
 hero:"Nana",
 name:"Sweet Leonin",
 role:"Mage",
 release:2016,
 Specialty:"Poke/Burst",
 lane:"Mid Lane",
 region:"Azrya Woodlands",
 id:5},{
 hero:"Tigreal",
 name:"Warrior of Dawn",
 role:"Tank",
 release:2016,
 Specialty:"Crowd Control",
 lane:"Roaming",
 region:"Moniyan Empire",
 id:6},{
 hero:"Alucard",
 name:"Demon Hunter",
 role:"Fighter/Assassin",
 release:2016,
 Specialty:"Chase/Damage",
 lane:"Jungle",
 region:"Moniyan Empire",
 id:7},{
 hero:"Karina",
 name:"Shadow Blade",
 role:"Assassin",
 release:2016,
 Specialty:"Finisher/Magic Damage",
 lane:"Jungle",
 region:"Azrya Woodlands",
 id:8},{
 hero:"Akai",
 name:"Panda Warrior",
 role:"Tank",
 release:2016,
 Specialty:"Guard/Crowd Control",
 lane:"Roaming",
 region:"Cadia Riverlands",
 id:9},{
 hero:"Franco",
 name:"Frozen Warrior",
 role:"Tank",
 release:2016,
 Specialty:"Initiator/Control",
 lane:"Roaming",
 region:"Northern Vale",
 id:10},{
 hero:"Bane",
 name:"Frozen King",
 role:"Fighter/Mage",
 release:2016,
 Specialty:"Push/Burst",
 lane:"Jungle/EXP Lane",
 region:"Northern Vale",
 id:11},{
 hero:"Bruno",
 name:"Protector",
 role:"Marksman",
 release:2016,
 Specialty:"Finisher/Burst",
 lane:"Gold Lane",
 region:"Agelta Drylands",
 id:12},{
 hero:"Clint",
 name:"West Justice",
 role:"Marksman",
 release:2016,
 Specialty:"Finisher/Burst",
 lane:"Gold Lane",
 region:"Agelta Drylands",
 id:13},{
 hero:"Rafaela",
 name:"Wings of Holiness",
 role:"Support",
 release:2016,
 Specialty:"Regen/Guard",
 lane:"Roaming",
 region:"Moniyan Empire",
 id:14},{
 hero:"Eudora",
 name:"Lightning Weaver",
 role:"Mage",
 release:2016,
 Specialty:"Control/Burst",
 lane:"Mid Lane",
 region:"Northern Vale",
 id:15},{
 hero:"Zilong",
 name:"Spear of Dragon",
 role:"Fighter/Assassin",
 release:2016,
 Specialty:"Chase/Damage",
 lane:"EXP Lane",
 region:"Cadia Riverlands",
 id:16},{
 hero:"Fanny",
 name:"Blade Dancer",
 role:"Assassin",
 release:2016,
 Specialty:"Chase/Finisher",
 lane:"Jungle",
 region:"Moniyan Empire",
 id:17},{
 hero:"Layla",
 name:"Energy Gunner",
 role:"Marksman",
 release:2016,
 Specialty:"Finisher/Damage",
 lane:"Gold Lane",
 region:"Agelta Drylands",
 id:18},{
 hero:"Minotaur",
 name:"Son of Minos",
 role:"Tank/Support",
 release:2016,
 Specialty:"Crowd Control",
 lane:"Roaming",
 region:"Agelta Drylands",
 id:19},{
 hero:"Lolita",
 name:"Steel Elf",
 role:"Support/Tank",
 release:2016,
 Specialty:"Guard/Crowd Control",
 lane:"Roaming",
 region:"Agelta Drylands",
 id:20},{
 hero:"Hayabusa",
 name:"Crimson Shadow",
 role:"Assassin",
 release:2016,
 Specialty:"Chase/Burst",
 lane:"Jungle",
 region:"Cadia Riverlands",
 id:21},{
 hero:"Freya",
 name:"Valkyrie",
 role:"Fighter",
 release:2016,
 Specialty:"Chase/Damage",
 lane:"EXP Lane/Jungle",
 region:"Northern Vale",
 id:22},{
 hero:"Gord",
 name:"Professor of the Mystic",
 role:"Mage",
 release:2016,
 Specialty:"Poke/Burst",
 lane:"Mid Lane",
 region:"Nebula Chronorift",
 id:23},{
 hero:"Natalia",
 name:"Bright Claw",
 role:"Assassin",
 release:2016,
 Specialty:"Chase/Finisher",
 lane:"Roaming/Jungle",
 region:"Moniyan Empire",
 id:24},{
 hero:"Kagura",
 name:"Onmyouji Master",
 role:"Mage",
 release:2016,
 Specialty:"Poke/Finisher",
 lane:"Mid Lane",
 region:"Cadia Riverlands",
 id:25},{
 hero:"Chou",
 name:"Kung Fu Boy",
 role:"Fighter",
 release:2016,
 Specialty:"Chase/Control",
 lane:"EXP Lane/Roaming",
 region:"Eruditio",
 id:26},{
 hero:"Sun",
 name:"Monkey King",
 role:"Fighter",
 release:2016,
 Specialty:"Push/Damage",
 lane:"EXP Lane/Jungle",
 region:"Cadia Riverlands",
 id:27},{
 hero:"Alpha",
 name:"Blade of Enmity",
 role:"Fighter",
 release:2017,
 Specialty:"Charge/Damage",
 lane:"Jungle/EXP Lane",
 region:"Agelta Drylands",
 id:28},{
 hero:"Ruby",
 name:"Little Red Hood",
 role:"Fighter",
 release:2017,
 Specialty:"Crowd Control/Regen",
 lane:"EXP Lane",
 region:"Moniyan Empire",
 id:29},{
 hero:"Yi Sun-shin",
 name:"Paenlong Legend",
 role:"Assassin/Marksman",
 release:2017,
 Specialty:"Finisher/Chase",
 lane:"Jungle/Gold Lane",
 region:"Cadia Riverlands",
 id:30},{
 hero:"Moskov",
 name:"Spear of Quiescence",
 role:"Marksman",
 release:2017,
 Specialty:"Finisher/Chase",
 lane:"Gold Lane",
 region:"Agelta Drylands",
 id:31},{
 hero:"Johnson",
 name:"Wild Engine",
 role:"Tank/Support",
 release:2017,
 Specialty:"Support/Crowd Control",
 lane:"Roaming",
 region:"Agelta Drylands",
 id:32},{
 hero:"Cyclops",
 name:"Starsoul Magician",
 role:"Mage",
 release:2017,
 Specialty:"Poke/Control",
 lane:"Mid Lane",
 region:"Nebula Chronorift",
 id:33},{
 hero:"Estes",
 name:"Moon Elf King",
 role:"Support",
 release:2017,
 Specialty:"Regen/Guard",
 lane:"Roaming",
 region:"Azrya Woodlands",
 id:34},{
 hero:"Hilda",
 name:"Power of Megalith",
 role:"Fighter/Tank",
 release:2017,
 Specialty:"Damage/Regen",
 lane:"Roaming/EXP Lane",
 region:"Northern Vale",
 id:35},{
 hero:"Aurora",
 name:"Maiden of the Glacier",
 role:"Mage",
 release:2017,
 Specialty:"Crowd Control/Poke",
 lane:"Mid Lane",
 region:"Northern Vale",
 id:36},{
 hero:"Lapu-Lapu",
 name:"Courageous Blade",
 role:"Fighter",
 release:2017,
 Specialty:"Chase/Burst",
 lane:"EXP Lane",
 region:"Vonetis Sea",
 id:37},{
 hero:"Vexana",
 name:"Shimmer of Hope",
 role:"Mage",
 release:2017,
 Specialty:"Poke/Control",
 lane:"Mid Lane",
 region:"The Barren Lands",
 id:38},{
 hero:"Roger",
 name:"Dire Wolf Hunter",
 role:"Fighter/Marksman",
 release:2017,
 Specialty:"Finisher/Burst",
 lane:"Jungle",
 region:"Moniyan Empire",
 id:39},{
 hero:"Karrie",
 name:"Lost Star",
 role:"Marksman",
 release:2017,
 Specialty:"Finisher/Damage",
 lane:"Gold Lane",
 region:"Alaghat",
 id:40},{
 hero:"Gatotkaca",
 name:"Mighty Legend",
 role:"Tank/Fighter",
 release:2017,
 Specialty:"Crowd Control/Burst",
 lane:"Roaming/EXP Lane",
 region:"Nebula Chronorift",
 id:41},{
 hero:"Harley",
 name:"Mage Genius",
 role:"Assassin/Mage",
 release:2017,
 Specialty:"Burst/Poke",
 lane:"Jungle",
 region:"Northern Vale",
 id:42},{
 hero:"Irithel",
 name:"Jungle Heart",
 role:"Marksman",
 release:2017,
 Specialty:"Finisher/Burst",
 lane:"Gold Lane",
 region:"Azrya Woodlands",
 id:43},{
 hero:"Grock",
 name:"Fortress Titan",
 role:"Tank/Fighter",
 release:2017,
 Specialty:"Crowd Control/Initiator",
 lane:"Roaming",
 region:"The Barren Lands",
 id:44},{
 hero:"Argus",
 name:"Dark Angel",
 role:"Fighter",
 release:2017,
 Specialty:"Charge/Burst",
 lane:"EXP Lane",
 region:"The Barren Lands",
 id:45},{
 hero:"Odette",
 name:"Swan Princess",
 role:"Mage",
 release:2017,
 Specialty:"Burst/Poke",
 lane:"Mid Lane",
 region:"Moniyan Empire",
 id:46},{
 hero:"Lancelot",
 name:"Blade of Roses",
 role:"Assassin",
 release:2017,
 Specialty:"Chase/Burst",
 lane:"Jungle",
 region:"Moniyan Empire",
 id:47},{
 hero:"Diggie",
 name:"Timekeeper",
 role:"Support",
 release:2017,
 Specialty:"Guard/Poke",
 lane:"Roaming",
 region:"Agelta Drylands",
 id:48},{
 hero:"Hylos",
 name:"Grand Warden",
 role:"Tank",
 release:2017,
 Specialty:"Guard/Initiator",
 lane:"Roaming",
 region:"Agelta Drylands",
 id:49},{
 hero:"Zhask",
 name:"King of Swarms",
 role:"Mage",
 release:2017,
 Specialty:"Chase/Damage",
 lane:"Mid Lane",
 region:"Kastiya",
 id:50},{
 hero:"Helcurt",
 name:"Shadowbringer",
 role:"Assassin",
 release:2017,
 Specialty:"Push/Burst",
 lane:"Jungle",
 region:"The Barren Lands",
 id:51},{
 hero:"Pharsa",
 name:"Wings of Vengeance",
 role:"Mage",
 release:2017,
 Specialty:"Burst/Poke",
 lane:"Mid Lane",
 region:"The Barren Lands",
 id:52},{
 hero:"Lesley",
 name:"Deadly Sniper",
 role:"Marksman/Assassin",
 release:2017,
 Specialty:"Finisher/Burst",
 lane:"Gold Lane",
 region:"Moniyan Empire",
 id:53},{
 hero:"Jawhead",
 name:"Steel Sweetheart",
 role:"Fighter",
 release:2018,
 Specialty:"Charge/Burst",
 lane:"Roaming/EXP Lane",
 region:"Laboratory 1718",
 id:54},{
 hero:"Angela",
 name:"Bunnylove",
 role:"Support",
 release:2018,
 Specialty:"Guard/Support",
 lane:"Roaming",
 region:"Laboratory 1718",
 id:55},{
 hero:"Gusion",
 name:"Holy Blade",
 role:"Assassin",
 release:2018,
 Specialty:"Burst/Magic Damage",
 lane:"Jungle",
 region:"Moniyan Empire",
 id:56},{
 hero:"Valir",
 name:"Son of Flames",
 role:"Mage",
 release:2018,
 Specialty:"Damage/Guard",
 lane:"Mid Lane",
 region:"Agelta Drylands",
 id:57},{
 hero:"Martis",
 name:"Ashura King",
 role:"Fighter",
 release:2018,
 Specialty:"Finisher/Charge",
 lane:"Jungle",
 region:"Nebula Chronorift",
 id:58},{
 hero:"Uranus",
 name:"Aesthereal Defender",
 role:"Tank",
 release:2018,
 Specialty:"Regen",
 lane:"EXP Lane",
 region:"Celestial Palace",
 id:59},{
 hero:"Hanabi",
 name:"Scarlet Flower",
 role:"Marksman",
 release:2018,
 Specialty:"Finisher/Damage",
 lane:"Gold Lane",
 region:"Cadia Riverlands",
 id:60},{
 hero:"Chang'e",
 name:"Moon Palace Immortal",
 role:"Mage",
 release:2018,
 Specialty:"Poke/Burst",
 lane:"Mid Lane",
 region:"Cadia Riverlands",
 id:61},{
 hero:"Kaja",
 name:"Nazar King",
 role:"Support/Fighter",
 release:2018,
 Specialty:"Control/Charge",
 lane:"Roaming",
 region:"Celestial Palace",
 id:62},{
 hero:"Selena",
 name:"Abyssal Witch",
 role:"Assassin/Mage",
 release:2018,
 Specialty:"Initiator/Finisher",
 lane:"Roaming/Mid Lane",
 region:"The Barren Lands",
 id:63},{
 hero:"Aldous",
 name:"Soul Contractor",
 role:"Fighter",
 release:2018,
 Specialty:"Burst/Support",
 lane:"EXP Lane",
 region:"Agelta Drylands",
 id:64},{
 hero:"Claude",
 name:"Master Thief",
 role:"Marksman",
 release:2018,
 Specialty:"Burst/Chase",
 lane:"Gold Lane",
 region:"Los Pecados",
 id:65},{
 hero:"Vale",
 name:"Windtalker",
 role:"Mage",
 release:2019,
 Specialty:"Burst/Crowd Control",
 lane:"Mid Lane",
 region:"Agelta Drylands",
 id:66},{
 hero:"Leomord",
 name:"Sworn Sword",
 role:"Fighter",
 release:2018,
 Specialty:"Chase/Burst",
 lane:"Jungle",
 region:"The Barren Lands",
 id:67},{
 hero:"Lunox",
 name:"Twilight Goddes",
 role:"Mage",
 release:2018,
 Specialty:"Burst/Damage",
 lane:"Mid Lane",
 region:"Agelta Drylands",
 id:68},{
 hero:"Hanzo",
 name:"Akuma Ninja",
 role:"Assassin",
 release:2018,
 Specialty:"Burst/Poke",
 lane:"Jungle",
 region:"Cadia Riverlands",
 id:69},{
 hero:"Belerick",
 name:"Guard of Nature",
 role:"Tank",
 release:2018,
 Specialty:"Crowd Control/Regen",
 lane:"Roaming",
 region:"Agelta Drylands",
 id:70},{
 hero:"Kimmy",
 name:"Hoverjet Outrider",
 role:"Marksman/Mage",
 release:2018,
 Specialty:"Damage/Magic Damage",
 lane:"Gold Lane/Mid Lane",
 region:"Eruditio",
 id:71},{
 hero:"Thamuz",
 name:"Lord Lava",
 role:"Fighter",
 release:2018,
 Specialty:"Chase/Damage",
 lane:"EXP Lane",
 region:"The Barren Lands",
 id:72},{
 hero:"Harith",
 name:"Time Traveler",
 role:"Mage",
 release:2018,
 Specialty:"Chase/Damage",
 lane:"Mid Lane/Gold Lane",
 region:"Moniyan Empire",
 id:73},{
 hero:"Minsitthar",
 name:"Courageous Warrior",
 role:"Fighter",
 release:2018,
 Specialty:"Initiator/Crowd Control",
 lane:"EXP Lane/Roaming",
 region:"Vonetis Sea",
 id:74},{
 hero:"Kadita",
 name:"Ocean Goddes",
 role:"Mage/Assassin",
 release:2018,
 Specialty:"Burst/Charge",
 lane:"Mid Lane",
 region:"Vonetis Sea",
 id:75},{
 hero:"Faramis",
 name:"Soul Binder",
 role:"Support/Mage",
 release:2019,
 Specialty:"Guard/Charge",
 lane:"Mid Lane",
 region:"The Barren Lands",
 id:76},{
 hero:"Badang",
 name:"Tribal Warrior",
 role:"Fighter",
 release:2019,
 Specialty:"Charge/Burst",
 lane:"EXP Lane",
 region:"Vonetis Sea",
 id:77},{
 hero:"Khufra",
 name:"Dessert Tyrant",
 role:"Tank",
 release:2019,
 Specialty:"Initiator/Crowd Control",
 lane:"Roaming",
 region:"Agelta Drylands",
 id:78},{
 hero:"Granger",
 name:"Death Chanter",
 role:"Marksman",
 release:2019,
 Specialty:"Burst/Finisher",
 lane:"Gold Lane",
 region:"Moniyan Empire",
 id:79},{
 hero:"Guinevere",
 name:"Ms. Violet",
 role:"Fighter",
 release:2019,
 Specialty:"Burst/Magic Damage",
 lane:"EXP Lane",
 region:"Moniyan Empire",
 id:80},{
 hero:"Esmeralda",
 name:"Astrologer",
 role:"Tank/Mage",
 release:2019,
 Specialty:"Regen/Mixed Damage",
 lane:"EXP Lane",
 region:"Agelta Drylands",
 id:81},{
 hero:"Terizla",
 name:"Executioner",
 role:"Fighter/Tank",
 release:2019,
 Specialty:"Burst/Crowd Control",
 lane:"EXP Lane",
 region:"The Barren Lands",
 id:82},{
 hero:"X.Borg",
 name:"Firaga Armor",
 role:"Fighter",
 release:2019,
 Specialty:"Regen/Burst",
 lane:"EXP Lane",
 region:"Agelta Drylands",
 id:83},{
 hero:"Ling",
 name:"Cyan Finch",
 role:"Assassin",
 release:2019,
 Specialty:"Chase/Burst",
 lane:"Jungle",
 region:"Cadia Riverlands",
 id:84},{
 hero:"Dyrroth",
 name:"Prince of the Abyss",
 role:"Fighter",
 release:2019,
 Specialty:"Charge/Burst",
 lane:"EXP Lane/Jungle",
 region:"The Barren Lands",
 id:85},{
 hero:"Lylia",
 name:"Little Witch",
 role:"Mage",
 release:2019,
 Specialty:"Push/Damage",
 lane:"Mid Lane",
 region:"Northern Vale",
 id:86},{
 hero:"Baxia",
 name:"Mystic Tortoise",
 role:"Tank",
 release:2019,
 Specialty:"Support/Damage",
 lane:"Jungle",
 region:"Cadia Riverlands",
 id:87},{
 hero:"Masha",
 name:"Wild-oats Fist",
 role:"Fighter/Tank",
 release:2019,
 Specialty:"Push/Damage",
 lane:"EXP Lane",
 region:"Northern Vale",
 id:88},{
 hero:"Wanwan",
 name:"Agile Tiger",
 role:"Marksman",
 release:2019,
 Specialty:"Finisher/Burst",
 lane:"Gold Lane",
 region:"Cadia Riverlands",
 id:89},{
 hero:"Silvanna",
 name:"Imperial Knightess",
 role:"Fighter",
 release:2019,
 Specialty:"Initiator/Magic Damage",
 lane:"EXP Lane",
 region:"Moniyan Empire",
 id:90},{
 hero:"Cecilion",
 name:"Embrance of Night",
 role:"Mage",
 release:2020,
 Specialty:"Poke/Burst",
 lane:"Mid Lane",
 region:"Moniyan Empire",
 id:91},{
 hero:"Carmilla",
 name:"Shadow of Twilight",
 role:"Support/Tank",
 release:2020,
 Specialty:"Crowd Control/Damage",
 lane:"Roaming",
 region:"Moniyan Empire",
 id:92},{
 hero:"Atlas",
 name:"Ocean Gladiator",
 role:"Tank",
 release:2020,
 Specialty:"Crowd Control/Initiator",
 lane:"Roaming",
 region:"Northern Vale",
 id:93},{
 hero:"Popol and Kupa",
 name:"Icefield Companions",
 role:"Marksman",
 release:2020,
 Specialty:"Push/Burst",
 lane:"Jungle/Gold Lane",
 region:"Northern Vale",
 id:94},{
 hero:"Yu Zhong",
 name:"Black Dragon",
 role:"Fighter",
 release:2020,
 Specialty:"Regen/Damage",
 lane:"EXP Lane",
 region:"Cadia Riverlands",
 id:95},{
 hero:"Luo Yi",
 name:"Yin-yang Geomancer",
 role:"Mage",
 release:2020,
 Specialty:"Support/Crowd Control",
 lane:"Mid Lane",
 region:"Cadia Riverlands",
 id:96},{
 hero:"Benedetta",
 name:"Shadow Ranger",
 role:"Assassin/Fighter",
 release:2020,
 Specialty:"Chase/Burst",
 lane:"EXP Lane",
 region:"The Barren Lands",
 id:97},{
 hero:"Khaleed",
 name:"Dessert Scimitar",
 role:"Fighter",
 release:2020,
 Specialty:"Damage/Regen",
 lane:"EXP Lane",
 region:"Agelta Drylands",
 id:98},{
 hero:"Barats",
 name:"Dino Rider",
 role:"Tank/Fighter",
 release:2020,
 Specialty:"Damage/Crowd Control",
 lane:"Jungle",
 region:"Agelta Drylands",
 id:99},{
 hero:"Brody",
 name:"Lone Star",
 role:"Marksman",
 release:2020,
 Specialty:"Burst/Finisher",
 lane:"Gold Lane",
 region:"The Barren Lands",
 id:100},{
 hero:"Yve",
 name:"Astrowarden",
 role:"Mage",
 release:2021,
 Specialty:"Burst/Poke",
 lane:"Mid Lane",
 region:"Northern Vale",
 id:101},{
 hero:"Mathilda",
 name:"Swift Plume",
 role:"Support/Assassin",
 release:2020,
 Specialty:"Initiator/Guard",
 lane:"Roaming",
 region:"Los Pecados",
 id:102},{
 hero:"Paquito",
 name:"Heavenly Fist",
 role:"Fighter/Assassin",
 release:2021,
 Specialty:"Chase/Damage",
 lane:"EXP Lane",
 region:"The Barren Lands",
 id:103},{
 hero:"Gloo",
 name:"Swamp Spirits",
 role:"Tank",
 release:2021,
 Specialty:"Regen/Control",
 lane:"EXP Lane/Roaming",
 region:"Azrya Woodlands",
 id:104},{
 hero:"Beatrix",
 name:"Dawnbreak Soldier",
 role:"Marksman",
 release:2021,
 Specialty:"Finisher/Damage",
 lane:"Gold Lane",
 region:"Agelta Drylands",
 id:105},{
 hero:"Phoveus",
 name:"Chains of Sin",
 role:"Fighter",
 release:2021,
 Specialty:"Regen/Damage",
 lane:"EXP Lane",
 region:"The Barren Lands",
 id:106},{
 hero:"Natan",
 name:"Spacetime Walker",
 role:"Marksman",
 release:2021,
 Specialty:"Burst/Magic Damage",
 lane:"Gold Lane",
 region:"Agelta Drylands",
 id:107},{
 hero:"Aulus",
 name:"Warrior of Ferocity",
 role:"Fighter",
 release:2021,
 Specialty:"Damage/Crowd Control",
 lane:"Jungle",
 region:"The Barren Lands",
 id:108},{
 hero:"Aamon",
 name:"Duke of Shards",
 role:"Assassin",
 release:2021,
 Specialty:"Chase/Magic Damage",
 lane:"Jungle",
 region:"Moniyan Empire",
 id:109},{
 hero:"Valentina",
 name:"Prophetess of the Night",
 role:"Mage",
 release:2021,
 Specialty:"Burst/Finisher",
 lane:"Mid Lane",
 region:"Moniyan Empire",
 id:110},{
 hero:"Edith",
 name:"Ancient Guard",
 role:"Tank/Marksman",
 release:2021,
 Specialty:"Control/Burst",
 lane:"EXP Lane/Roaming",
 region:"Sanctum Island",
 id:111},{
 hero:"Floryn",
 name:"Budding Hope",
 role:"Support",
 release:2021,
 Specialty:"Poke/Guard",
 lane:"Roaming",
 region:"Agelta Drylands",
 id:112},{
 hero:"Yin",
 name:"Martial Genius",
 role:"Fighter/Assassin",
 release:2022,
 Specialty:"Burst/Control",
 lane:"Jungle/EXP Lane",
 region:"Cadia Riverlands",
 id:113},{
 hero:"Melissa",
 name:"Cursed Needle",
 role:"Marksman",
 release:2022,
 Specialty:"Finisher/Damage",
 lane:"Gold Lane",
 region:"Moniyan Empire",
 id:114},{
 hero:"Xavier",
 name:"Defier of Light",
 role:"Mage",
 release:2022,
 Specialty:"Damage/Guard",
 lane:"Mid Lane",
 region:"Moniyan Empire",
 id:115},{
 hero:"Julian",
 name:"Scarlet Raven",
 role:"Assassin/Fighter",
 release:2022,
 Specialty:"Chase/Magic Damage",
 lane:"Jungle",
 region:"Moniyan Empire",
 id:116},{
 hero:"Fredrinn",
 name:"Rogue Appraiser",
 role:"Fighter/Tank",
 release:2022,
 Specialty:"Damage/Chase",
 lane:"Jungle",
 region:"Los Pecados",
 id:117},{
 hero:"Joy",
 name:"Flash of Miracle",
 role:"Assassin",
 release:2022,
 Specialty:"Chase/Damage",
 lane:"Jungle",
 region:"Azrya Woodlands",
 id:118},{
 hero:"Novaria",
 name:"Star Rebel",
 role:"Mage",
 release:2023,
 Specialty:"Burst/Poke",
 lane:"Mid Lane",
 region:"Agelta Drylands",
 id:119},{
 hero:"Arlott",
 name:"Lone Lancer",
 role:"Fighter/Assassin",
 release:2023,
 Specialty:"Charge/Burst",
 lane:"EXP Lane",
 region:"Moniyan Empire",
 id:120},{
 hero:"Ixia",
 name:"Arclight Outlaw",
 role:"Marksman",
 release:2023,
 Specialty:"Finisher/Damage",
 lane:"Gold Lane",
 region:"Agelta Drylands",
 id:121},{
 hero:"Nolan",
 name:"Cosmic Wayfinder",
 role:"Assassin",
 release:2023,
 Specialty:"Chase/Burst",
 lane:"Jungle",
 region:"Agelta Drylands",
 id:122},{
 hero:"Cici",
 name:"Buoyant Performer",
 role:"Fighter",
 release:2023,
 Specialty:"Damage/Regen",
 lane:"EXP Lane",
 region:"Moniyan Empire",
 id:123},{
 hero:"Chip",
 name:"Phase Technician",
 role:"Support/Tank",
 release:2024,
 Specialty:"Support/Crowd Control",
 lane:"Roaming",
 region:"Laboratory 1718",
 id:124},{
 hero:"Zhuxin",
 name:"Beacon of Spirits",
 role:"Mage",
 release:2024,
 Specialty:"Damage/Crowd Control",
 lane:"Mid Lane",
 region:"Cadia Riverlands",
 id:125},{
 hero:"Suyou",
 name:"Mask of the Immortal",
 role:"Assassin/Fighter",
 release:2024,
 Specialty:"Chase/Burst",
 lane:"Jungle",
 region:"Cadia Riverlands",
 id:126},{
 hero:"Lukas",
 name:"Beast of Light",
 role:"Fighter",
 release:2024,
 Specialty:"Regen/Damage",
 lane:"EXP Lane/Jungle",
 region:"Moniyan Empire",
 id:127},{
 hero:"Kalea",
 name:"Surging Wave",
 role:"Support/Fighter",
 release:2025,
 Specialty:"Control/Regen",
 lane:"Roaming",
 region:"Vonetis Sea",
 id:128},{
 hero:"Zetian",
 name:"Celestial Empress",
 role:"Mage",
 release:2025,
 Specialty:"Damage/Crowd Control",
 lane:"Mid Lane",
 region:"Cadia Riverlands",
 id:129,
}
];
