const dataHero = {
  "Cloud1":{
   "Aamon": ["Starlight", "Soul Vessel"], 
   "Akai": ["Halloween", "Anniversary", "Kungfu panda"], 
   "Aldous": ["Collector","Transformers", "Blazing", "Mistbender", "M1"], 
   "Alice": ["Luckybox"], 
   "Alpha": ["Luckybox", "Collector", "Legend"], 
   "Alucard": ["Luckybox", "Lightborn", "Star wars", "Legend"],
   "Angela": ["Starlight Gold","Collector", "Sanrio", "Kishin", "Aspirant"], 
   "Argus": ["Starlight", "Star wars", "Custom Epic"], 
   "Arlott": ["Starlight", "Collector", "Custom Obanai"], 
   "Atlas": ["Msc", "Starlight", "Collector"], 
   "Aulus": ["Special"], 
   "Aurora": ["Collector","Kof", "Zodiac"], 
   "Badang": ["Zodiac", "Collector", "Saint seiya Gold", "Custom Madara"], 
   "Balmond": ["Special", "Epic", "Collector"], 
   "Bane": ["Epic"], 
   "Barats": ["Epic"], 
   "Baxia": ["NoFile"], 
   "Beatrix": ["Starlight", "Mseries"], 
   "Belerick": ["Epic"], 
   "Benedetta": ["Special", "Starlight", "Mpl", "Ducati", "Covenant", "Collector"], 
   "Brody": ["Collector","Stun","Champion","Neobeast"], 
   "Bruno": ["Starlight", "Neymar", "Dawning"], 
   "Carmilla": ["Epic"], 
   "Cecilion": ["Starlight","Collector", "Hunter x hunter"], 
   "Change": ["Luckybox", "Lunar fest", "Aspirant", "Sanrio"], 
   "Chip": ["Elite"], 
   "Chou": ["Luckybox", "Champion", "Dawning", "Saint seiya Gold", "Kof", "Stun"], 
   "Cici": ["Starlight"], 
   "Claude": ["Luckybox", "Blazing", "M6", "Prime", "Sanrio", "Valentine"], 
   "Clint": ["Epic","Collector", "M2", "Mythic"], 
   "Cyclops": ["Collector","Star wars"], 
   "Diggie": ["Epic"], 
   "Dyrroth": ["Collector", "Venom", "Kof", "Hunter x hunter"],
   "Edith": ["Collector", "Mpl", "Clouds"], 
   "Esmeralda": ["Collector","Blazing", "Dawning"], 
   "Estes": ["Sparkle", "Champion"], 
   "Eudora": ["Starlight", "Luckybox", "Atomic"]
}, "Cloud2":{
   "Fanny": ["Luckybox", "Christmas", "Lightborn", "Summer", "Valentine", "Aot", "Aspirants"], 
   "Faramis": ["Summer", "Mythic"], 
   "Floryn": ["Collector", "Sanrio"], 
   "Franco": ["Epic", "Luckybox", "Mpl", "Blazing"], 
   "Fredrinn": ["Neobeast", "Sparkle"], 
   "Freya": ["Epic"], 
   "Gatotkaca": ["Epic", "Luckybox"], 
   "Gloo": ["Special"], 
   "Gord": ["Epic", "Starlight", "Starlight Gold", "Legend"], 
   "Granger": ["Collector", "Create", "Transformers", "Valentine", "Lightborn", "Exorcist", "Legend"], 
   "Grock": ["Epic", "Venom"], 
   "Guinevere": ["Epic", "Summer", "Kof", "Legend", "Custom Hinata"], 
   "Gusion": ["Epic","Collector", "Kof", "11.11", "Legend"], 
   "Hanabi": ["Collector", "Soul vessel", "Allstar"], 
   "Hanzo": ["Collector"], 
   "Harith": ["Collector", "Lightborn", "Champion", "Hunter x hunter"], 
   "Harley": ["Epic", "Collector"], 
   "Hayabusa": ["Epic", "Starlight Gold", "11.11", "Exorcist", "Kakashi", "Custom Itachi"], 
   "Helcurt": ["Zodiac", "Starlight"], 
   "Hilda": ["Zodiac"], 
   "Hylos": ["Epic"], 
   "Irithel": ["Luckybox", "Zodiac", "Ducati"], 
   "Ixia": ["Starlight"], 
   "Jawhead": ["Collector","Mpl", "Allstar"], 
   "Johnson": ["Luckybox", "Saber", "Legend"], 
   "Joy": ["Starlight"], 
   "Julian": ["Jujutsu kaisen", "Hunter x hunter", "Fatcat"], 
}, "Cloud3":{
   "Kadita": ["Starlight", "Create", "Mpl"], 
   "Kagura": ["Epic", "Luckybox", "Starlight", "Starlight Gold", "Exorcist", "Clouds"], 
   "Kaja": ["Epic", "Luckybox"], 
   "Kalea": ["Sakura"], 
   "Karina": ["Epic", "Luckybox", "Kof", "Zodiac"], 
   "Karrie": ["Luckybox", "Starlight Gold", "Kishin"], 
   "Khaleed": ["Epic"], 
   "Khufra": ["Starlight", "Collector", "Custom Epic"], 
   "Kimmy": ["Starlight", "Luckybox", "Star wars", "Dragon tamer"], 
   "Lancelot": ["Luckybox", "Christmas", "Dawning", "Zodiac", "Kishin", "Champion"], 
   "Lapu lapu": ["Special", "Starlight", "Collector"], 
   "Layla": ["Starlight","Collector", "Aspirant"], 
   "Leomord": ["Luckybox", "Abyss", "Ducati"], 
   "Lesley": ["Luckybox", "Starlight", "Starlight Gold", "Collector", "Aspirants", "Fatcat", "Covenant", "Legend"], 
   "Ling": ["Starlight","Collector", "Kungfu panda", "Dragon tamer", "Mworld", "Neobeast"], 
   "Lolita": ["NoFile"], 
   "Luo yi": ["Epic", "Starlight", "Collector"], 
   "Lukas": ["NoFile"], 
   "Lunox": ["Luckybox", "Zodiac", "Legend"], 
   "Lylia": ["Starlight", "Neobeast"], 
   "Martis": ["Luckybox", "Starlight", "Aot", "Zodiac"], 
   "Masha": ["Kof"], 
   "Mathilda": ["Epic", "Mpl"], 
   "Melissa": ["Starlight", "Jujutsu kaisen", "Sparkle", "Collector"], 
   "Minotaur": ["Zodiac"], 
   "Minsitthar": ["Starlight", "Collector"], 
   "Miya": ["Starlight","Collector", "Christmas", "Atomic", "Legend"], 
   "Moskov": ["Luckybox", "Abyss", "Allstar"], 
}, "Cloud4":{
   "Nana": ["Collector","Mistbender", "Custom Anya"], 
   "Natalia": ["Collector"], 
   "Natan": ["Collector"], 
   "Nolan": ["11.11"], 
   "Novaria": ["Starlight", "Collector"], 
   "Odette": ["Starlight", "Create", "Lunar fest", "Zodiac"], 
   "Paquito": ["Starlight","Collector", "Kof", "Fmvp", "Pacquiao"], 
   "Pharsa": ["Epic", "Starlight","Collector", "Msc", "Neobeast"], 
   "Phoveus": ["Starlight"], 
   "Popol and kupa": ["Collector","Transformers", "Allstar"], 
   "Rafaela": ["Mpl", "Lunar fest"], 
   "Roger": ["Epic", "M3", "Prime"], 
   "Ruby": ["Epic","Collector", "Aspirants"], 
   "Saber": ["Luckybox", "Legend"], 
   "Selena": ["Epic", "Abyss", "Stun", "Zodiac"], 
   "Silvanna": ["Collector", "Valentine", "Fatcat"], 
   "Sun": ["Starlight", "Collector"], 
   "Suyou": ["Sasuke"], 
   "Terizla": ["Epic", "Collector"], 
   "Thamuz": ["Starlight", "Kungfu panda"], 
   "Tigreal": ["Lightborn", "Starlight"], 
   "Uranus": ["Epic"], 
}, "Cloud5":{
   "Vale": ["Starlight Gold","Collector", "Dawning", "Gaara"],
   "Valentina": ["Starlight","Collector", "Msc"], 
   "Valir": ["Collector","Kof", "Saint seiya Gold", "Legend"],
   "Vexana": ["Collector","Zenith"], 
   "Wanwan": ["Collector", "11.11", "Mworld"], 
   "X borg": ["Transformers", "11.11"], 
   "Xavier": ["Clouds", "Jujutsu kaisen"], 
   "Yi sun shin": ["Starlight", "Collector"], 
   "Yin": ["Aot", "Jujutsu kaisen", "Mworld", "Custom Obito"], 
   "Yu zhong": ["Starlight", "Collector", "M5", "Prime"], 
   "Yve": ["Elite"], 
   "Zetian": ["NoFile"], 
   "Zhask": ["Luckybox", "Starlight", "Zodiac"], 
   "Zhuxin": ["Starlight"], 
   "Zilong": ["Epic", "Lunar Fest"], 
 }
};
