const dataHero = {
  "cloud1":{
   "Aamon":{
    info:["Assassin","2021"],
    skin:["Starlight","Soul vessel"]},
   "Akai":{
    info:["Tank","2016"],
    skin:["Halloween","Kunfu panda"]},
   "Aldous":{
    info:["Fighter","2018"],
    skin:["Blazing","Mistbender","Collector"]},
   "Alice":{
    info:["Mage/Tank","2016"],
    skin:["Epic"]},
   "Alpha":{
    info:["Fighter","2017"],
    skin:["Epic","Collector","Legend"]},
   "Alucard":{
    info:["Fighter/Assassin","2016"],
    skin:["Star wars","Legend"]},
   "Angela":{
    info:["Support","2018"],
    skin:["Sanrio","Kishin","Aspirant","Collector"]},
   "Argus":{
    info:["Fighter","2017"],
    skin:["Epic","Star wars"]},
   "Arlott":{
    info:["Fighter/Assassin","2023"],
    skin:["Collector"]},
   "Atlas":{
    info:["Tank","2020"],
    skin:["Collector"]},
   "Aulus":{
    info:["Fighter","2021"],
    skin:["Special"]},
   "Aurora":{
    info:["Mage","2017"],
    skin:["Kof","Zodiac","Collector"]},
   "Badang":{
    info:["Fighter","2019"],
    skin:["Zodiac","Collector"]},
   "Balmond":{
    info:["Fighter","2016"],
    skin:["Collector"]},
   "Bane":{
    info:["Fighter/Mage","2016"],
    skin:["Epic"]},
   "Barats":{
    info:["Tank/Fighter","2020"],
    skin:["Epic"]},
   "Baxia":{
    info:["Tank","2019"],
    skin:["NoFile"]},
   "Beatrix":{
    info:["Marksman","2021"],
    skin:["Mseries"]},
   "Belerick":{
    info:["Tank","2018"],
    skin:["Epic"]},
   "Benedetta":{
    info:["Assassin/Fighter","2020"],
    skin:["Mpl","Ducati","Covenant","Collector"]},
   "Brody":{
    info:["Marksman","2020"],
    skin:["Neobeast","Stun","Collector"]},
   "Bruno":{
    info:["Marksman","2016"],
    skin:["Dawning"]},
   "Carmilla":{
    info:["Support/Tank","2020"],
    skin:["Epic"]},
   "Cecilion":{
    info:["Mage","2020"],
    skin:["Hunter x hunter","Collector"]},
   "Change":{
    info:["Mage","2018"],
    skin:["Aspirant","Sanrio"]},
   "Chip":{
    info:["Support/Tank","2024"],
    skin:["NoFile"]},
   "Chou":{
    info:["Fighter","2016"],
    skin:["Dawning","Kof","Stun"]},
   "Cici":{
    info:["Fighter","2023"],
    skin:["Starlight"]},
   "Claude":{
    info:["Marksman","2018"],
    skin:["Prime","Sanrio"]},
   "Clint":{
    info:["Marksman","2016"],
    skin:["Epic","Mythic","Collector"]},
   "Cyclops":{
    info:["Mage","2017"],
    skin:["Star wars","Collector"]},
   "Diggie":{
    info:["Support","2017"],
    skin:["Epic"]},
   "Dyrroth":{
    info:["Fighter","2019"],
    skin:["Kof","Hunter x hunter","Collector"]},
   "Edith":{
    info:["Tank/Marksman","2021"],
    skin:["Clouds","Collector"]},
   "Esmeralda":{
    info:["Tank/Mage","2019"],
    skin:["Dawning","Collector"]},
   "Estes":{
    info:["Support","2017"],
    skin:["Sparkle"]},
   "Eudora":{
    info:["Mage","2016"],
    skin:["Atomic"]}
},"cloud2":{
   "Fanny":{
    info:["Assassin","2016"],
    skin:["Christmas","Lightborn","Summer","Luckybox","Aot","Aspirants"]},
   "Faramis":{
    info:["Support/Mage","2019"],
    skin:["mythic"]},
   "Floryn":{
    info:["Support","2021"],
    skin:["Sanrio","Collector"]},
   "Franco":{
    info:["Tank","2016"],
    skin:["Epic","Legend"]},
   "Fredrinn":{
    info:["Fighter/Tank","2022"],
    skin:["Neobeast","Sparkle"]},
   "Freya":{
    info:["Fighter","2016"],
    skin:["Legend"]},
   "Gatotkaca":{
    info:["Tank/Fighter","2017"],
    skin:["Epic","Luckybox"]},
   "Gloo":{
    info:["Tank","2021"],
    skin:["Special"]},
   "Gord":{
    info:["Mage","2016"],
    skin:["Starlight","Legend"]},
   "Granger":{
    info:["Marksman","2019"],
    skin:["Transformers","Lightborn","Exorcist","Collector","Legend"]},
   "Grock":{
    info:["Tank/Fighter","2017"],
    skin:["Epic","Venom"]},
   "Guinevere":{
    info:["Fighter","2019"],
    skin:["Kof","Legend"]},
   "Gusion":{
    info:["Assassin","2018"],
    skin:["Kof","11.11","Collector","Legend"]},
   "Hanabi":{
    info:["Marksman","2018"],
    skin:["Soul vessel","Allstar","Collector"]},
   "Hanzo":{
    info:["Assassin","2018"],
    skin:["Collector"]},
   "Harith":{
    info:["Mage","2018"],
    skin:["Hunter x hunter","Collector"]},
   "Harley":{
    info:["Assassin/Mage","2017"],
    skin:["Epic","Collector"]},
   "Hayabusa":{
    info:["Assassin","2016"],
    skin:["Epic","11.11","Exorcist","Kakashi"]},
   "Helcurt":{
    info:["Assassin","2017"],
    skin:["Zodiac","Starlight"]},
   "Hilda":{
    info:["Fighter/Tank","2017"],
    skin:["Zodiac"]},
   "Hylos":{
    info:["Tank","2017"],
    skin:["Epic"]},
   "Irithel":{
    info:["Marksman","2017"],
    skin:["Zodiac","Ducati"]},
   "Ixia":{
    info:["Marksman","2023"],
    skin:["Starlight"]},
   "Jawhead":{
    info:["Fighter","2018"],
    skin:["Allstar","Collector"]},
   "Johnson":{
    info:["Tank/Support","2017"],
    skin:["Legend"]},
   "Joy":{
    info:["Assassin","2022"],
    skin:["Starlight"]},
   "Julian":{
    info:["Assassin/Fighter","2022"],
    skin:["Jujutsu kaisen","Hunter x hunter","Fatcat"]},
},"cloud3":{
   "Kadita":{
    info:["Mage/Assassin","2018"],
    skin:["Starlight"]},
   "Kagura":{
    info:["Mage","2016"],
    skin:["Clouds","Exorcist","Luckybox"]},
   "Kaja":{
    info:["Support/Fighter","2018"],
    skin:["Epic"]},
   "Kalea":{
    info:["Support/Fighter","2025"],
    skin:["Sakura"]},
   "Karina":{
    info:["Assassin","2016"],
    skin:["Epic","Kof","Zodiac"]},
   "Karrie":{
    info:["Marksman","2017"],
    skin:["Kishin"]},
   "Khaleed":{
    info:["Fighter","2020"],
    skin:["Epic"]},
   "Khufra":{
    info:["Tank","2019"],
    skin:["Epic","Collector"]},
   "Kimmy":{
    info:["Marksman/Mage","2018"],
    skin:["Luckybox","Star wars","Dragon tamer"]},
   "Lancelot":{
    info:["Assassin","2017"],
    skin:["Dawning","Luckybox","Zodiac","Kishin","Champion"]},
   "Lapu lapu":{
    info:["Fighter","2017"],
    skin:["Collector"]},
   "Layla":{
    info:["Marksman","2016"],
    skin:["Aspirant","Collector"]},
   "Leomord":{
    info:["Fighter","2018"],
    skin:["Epic","Abyss","Ducati"]},
   "Lesley":{
    info:["Marksman/Assassin","2018"],
    skin:["Aspirants","Collector","Legend"]},
   "Ling":{
    info:["Assassin","2019"],
    skin:["Kungfu panda","Dragon tamer","Mworld","Neobeast","Collector"]},
   "Lolita":{
    info:["Support/Tank","2016"],
    skin:["NoFile"]},
   "Lou yi":{
    info:["Mage","2020"],
    skin:["Epic","Collector"]},
   "Lukas":{
    info:["Fighter","2024"],
    skin:["Naruto"]},
   "Lunox":{
    info:["Mage","2018"],
    skin:["Zodiac","Legend"]},
   "Lylia":{
    info:["Mage","2019"],
    skin:["Neobeast"]},
   "Martis":{
    info:["Fighter","2018"],
    skin:["Aot","Zodiac"]},
   "Masha":{
    info:["Fighter/Tank","2019"],
    skin:["Kof"]},
   "Mathilda":{
    info:["Support/Assassin","2020"],
    skin:["Epic"]},
   "Melissa":{
    info:["Marksman","2022"],
    skin:["Jujutsu kaisen","Sparkle","Collector"]},
   "Minotaur":{
    info:["Tank/Support","2016"],
    skin:["Zodiac"]},
   "Minsitthar":{
    info:["Fighter","2018"],
    skin:["Collector"]},
   "Miya":{
    info:["Marksman","2016"],
    skin:["Atomic","Collector","Legend"]},
   "Moskov":{
    info:["Marksman","2017"],
    skin:["Abyss","Allstar"]},
},"cloud4":{
   "Nana":{
    info:["Mage","Po","2016"],
    skin:["Mistbender","Collector"]},
   "Natalia":{
    info:["Assassin","2016"],
    skin:["Collector"]},
   "Natan":{
    info:["Marksman","2021"],
    skin:["Collector"]},
   "Nolan":{
    info:["Assassin","2023"],
    skin:["11.11"]},
   "Novaria":{
    info:["Mage","2023"],
    skin:["Collector"]},
   "Odette":{
    info:["Mage","2017"],
    skin:["Starlight","Zodiac"]},
   "Paquito":{
    info:["Fighter/Assassin","2021"],
    skin:["Kof","Collector"]},
   "Pharsa":{
    info:["Mage","2017"],
    skin:["Epic","Neobeast","Collector"]},
   "Phoveus":{
    info:["Fighter","2021"],
    skin:["Starlight"]},
   "Popol and kupa":{
    info:["Marksman","2020"],
    skin:["Transformers","Collector"]},
   "Rafaela":{
    info:["Support","2016"],
    skin:["Lunar fest"]},
   "Roger":{
    info:["Fighter/Marksman","2017"],
    skin:["Prime"]},
   "Ruby":{
    info:["Fighter","2017"],
    skin:["Aspirants","Collector"]},
   "Saber":{
    info:["Assassin","2016"],
    skin:["Legend"]},
   "Selena":{
    info:["Assassin/Mage","2018"],
    skin:["Abyss","Stun","Zenith","Zodiac"]},
   "Silvanna":{
    info:["Fighter","2019"],
    skin:["Valentine","Fatcat"]},
   "Sun":{
    info:["Fighter","2016"],
    skin:["Collector"]},
   "Suyou":{
    info:["Assassin/Fighter","2024"],
    skin:["Sasuke"]},
   "Terizla":{
    info:["Fighter/Tank","2019"],
    skin:["Collector"]},
   "Thamuz":{
    info:["Fighter","2018"],
    skin:["Kunfu panda"]},
   "Tigreal":{
    info:["Tank","2016"],
    skin:["Lightborn","Starlight"]},
   "Uranus":{
    info:["Tank","2018"],
    skin:["Epic"]},
},"cloud5":{
   "Vale":{
    info:["Mage","2019"],
    skin:["Dawning","Collector"]},
   "Valentina":{
    info:["Mage","2021"],
    skin:["Collector"]},
   "Valir":{
    info:["Mage","2018"],
    skin:["Kof","Collector"]},
   "Vexana":{
    info:["Mage","2017"],
    skin:["Zenith","Collector"]},
   "Wanwan":{
    info:["Marksman","2019"],
    skin:["11.11","Mworld","Collector"]},
   "X borg":{
    info:["Fighter","2019"],
    skin:["Transformers","11.11"]},
   "Xavier":{
    info:["Mage","2022"],
    skin:["Jujutsu kaisen","Clouds"]},
   "Yi sun shin":{
    info:["Assassin/Marksman","2017"],
    skin:["Collector"]},
   "Yin":{
    info:["Fighter/Assassin","2022"],
    skin:["Aot","Jujutsu kaisen","Mworld"]},
   "Yu zhong":{
    info:["Fighter","2020"],
    skin:["Exorcist","Collector"]},
   "Yve":{
    info:["Mage","2021"],
    skin:["NoFile"]},
   "Zhask":{
    info:["Mage","2017"],
    skin:[",Zodiac"]},
   "Zhuxin":{
    info:["Mage","2024"],
    skin:["Starlight"]},
   "Zilong":{
    info:["Fighter/Assassin","2016"],
    skin:["Collector"]},
 }
};
