const heroes = {
 zyHero: {
  zyVoid: [
   "Aamon Soul vessel",
   "Aamon Starlight",
   "Akai Halloween",
   "Akai Kunfu panda",
   "Aldous Collector",
   "Aldous Mistbender",
   "Alpha Legend",
   "Alucard Star wars",
   "Angela Aspirant",
   "Angela Kishin",
   "Argus Star wars",
   "Aurora Kof",
   "Balmond Collector",
   "Benedetta Collector",
   "Benedetta Ducati",
   "Brody Neobeast",
   "Brody Stun",
   "Bruno Dawning",
   "Cecilion Hxh",
   "Chou Kof",
   "Claude Prime",
   "Claude Sanrio",
   "Clint Collector",
   "Cyclops Star wars",
   "Edith Clouds",
   "Eudora Atomic",
  ],zyVoid1: [
   "Fanny Aot",
   "Fanny Aspirants",
   "Fanny Luckybox",
   "Floryn Collector",
   "Floryn Sanrio",
   "Fredrinn Neobeast",
   "Freya Legend",
   "Gatotkaca Luckybox",
   "Gord Legend",
   "Granger Collector",
   "Granger Exorcist",
   "Granger Legend",
   "Granger Transformers",
   "Guinevere Kof",
   "Gusion Legend",
   "Hanabi Soul vessel",
   "Hanzo Collector",
   "Harith Hxh",
   "Hayabusa 11.11",
   "Hayabusa Epic",
   "Hayabusa Exorcist",
   "Hayabusa Kakashi",
   "Jawhead Collector",
   "Johnson Legend",
   "Julian Hxh",
   "Julian Jjk",
  ],zyVoid2: [
   "Kagura Clouds",
   "Kagura Exorcist",
   "Kagura Luckybox",
   "Kagura Starlightgold",
   "Kalea Sakura",
   "Karina Epic",
   "Karina Kof",
   "Karina Zodiac",
   "Karrie Kishin",
   "Kimmy Luckybox",
   "Lancelot Dawning",
   "Lancelot Kishin",
   "Lancelot Luckybox",
   "Layla Aspirant",
   "Layla Collector",
   "Leomord Ducati",
   "Lesley Aspirant",
   "Lesley Legend",
   "Ling Collector",
   "Ling Kunfu panda",
   "Ling Neobeast",
   "Lukas Naruto",
   "Lunox Legend",
   "Lunox Zodiac",
   "Lylia Neobeast",
   "Martis Aot",
   "Masha Kof",
   "Melissa Jjk",
   "Minotaur Zodiac",
   "Miya Atomic",
   "Miya Legend",
   "Moskov Allstar",
  ],zyVoid3: [
   "Nana Collector",
   "Natan Collector",
   "Novaria Collector",
   "Paquito Collector",
   "Paquito Kof",
   "Pharsa Neobeast",
   "Phoveus Starlight",
   "Popol Collector",
   "Popol Transformers",
   "Ruby Aspirant",
   "Saber Legend",
   "Selena Abyss",
   "Selena Stun",
   "Selena Zenith",
   "Selena Zodiac",
   "Sun Collector",
   "Suyou Naruto",
   "Thamuz Kunfu panda",
   "Tigreal Lightborn",
   "Tigreal Starlight",
   "Vale Naruto",
   "Valentina Collector",
   "Valir Kof",
   "Valir Legend",
   "Vexana Collector",
   "Vexana Zenith",
  ],zyVoid4: [
   "Xavier Jjk",
   "Xborg Transformers",
   "Yin Aot",
   "Yin Jjk",
   "Yu Zhong Collector",
   "Yuzhong Exorcist",
  ]
 }
};
